version: '3.5'

services:
  kafka-1:
    image: quay.io/yigitpolat/apache-kafka:s390x
    hostname: kafka-1
    ports:
      - 19092:19092
    networks:
      - zookeeper-apache-cluster-network
    volumes:
      - ${PWD}/../apache-kafka/conf/kafka-1-server.properties:/home/kafka/config/server.properties
  

  kafka-2:
    image: quay.io/yigitpolat/apache-kafka:s390x
    hostname: kafka-2
    ports:
      - 29092:29092
    networks:
      - zookeeper-apache-cluster-network
    volumes:
      - ${PWD}/../apache-kafka/conf/kafka-2-server.properties:/home/kafka/config/server.properties

  kafka-3:
    image: quay.io/yigitpolat/apache-kafka:s390x
    hostname: kafka-3
    ports:
      - 39092:39092
    networks:
      - zookeeper-apache-cluster-network
    volumes:
      - ${PWD}/../apache-kafka/conf/kafka-3-server.properties:/home/kafka/config/server.properties
  

networks:
  zookeeper-apache-cluster-network:
    external: true
    name: zookeeper-apache-cluster-network